apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir
  namespace: mimir
spec:
  rules:
    - host: mimir.local.gd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mimir-gateway
                port:
                  number: 80
