apiVersion: v2
name: kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: k8s-monitoring
    version: 1.4.6
    repository: https://grafana.github.io/helm-charts
