apiVersion: v2
name: mimir
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: mimir-distributed
    version: 5.4.0-weekly.292
    repository: https://grafana.github.io/helm-charts
