apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/fishst1k/lgtm-kind.git
    targetRevision: master
    path: argocd-simple/helm/grafana
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
