apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
spec:
  destination:
    namespace: k8s-monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/fishst1k/lgtm-kind.git
    targetRevision: master
    path: argocd/helm/k8s-monitoring
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
