apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fishst1k/lgtm-kind.git
    targetRevision: master
    path: argocd/ingress/grafana
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
