apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: mimir
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/fishst1k/lgtm-kind.git
    targetRevision: master
    path: argocd/helm/mimir
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true